:- module('TDA-pixrgb',[pixrgb/7,isPixrgb/1,select_pixrgb_x/2,select_pixrgb_y/2,select_pixrgb_red/2,select_pixrgb_green/2,select_pixrgb_blue/2,select_pixrgb_depth/2,mod_pixrgb_x/3,mod_pixrgb_y/3,mod_pixrgb_red/3,mod_pixrgb_green/3,mod_pixrgb_blue/3,mod_pixrgb_depth/3]).

%TDA-PIXRGB
%ENTERO X ENTERO X ENTERO X ENTERO X ENTERO

%PIXRGB
% UNIFICA LOS VALORES ENTEROS ENTREGADOS CON UN TDA:PIXRGB CUYO
% CONTENIDO SON DICHOS ENTEROS.
% DOMINIO: ENTERO X ENTERO X ENTERO (0-255) X ENTERO (0-255) X ENTERO
% (0-255) X ENTERO X TDA:PIXRGB.

pixrgb(X,Y,R,G,B,D,[X,Y,R,G,B,D]).

%ISPIXRGB
% EVALUA SI UN ELEMENTO INGRESADO ES UN TDA:PIXRGB.
% DOMINIO: ANY

isPixrgb([X,Y,R,G,B,D|[]]):-integer(X),integer(Y),X > -1,Y > -1, integer(R), R > -1, R < 256, integer(G), G > -1, G < 256, integer(B), B > -1, B < 256, integer(D).

%SELECT_PIXRGB_X
% UNIFICA EL PRIMER ELEMENTO DE UN TDA:PIXRGB CON UN ELEMENTO X, COMO
% PROTOSALIDA.
% DOMINIO: TDA:PIXRGB X ENTERO

select_pixrgb_x([X|PB],X):- isPixrgb([X|PB]).

%SELECT_PIXRGB_Y
% UNIFICA EL SEGUNDO ELEMENTO DE UN TDA:PIXRGB CON UN ELEMENTO Y, COMO
% PROTOSALIDA.
% DOMINIO: TDA:PIXRGB X ENTERO

select_pixrgb_y([X,Y|PB],Y):- isPixrgb([X,Y|PB]).

%SELECT_PIXRGB_RED
% UNIFICA EL TERCER ELEMENTO DE UN TDA:PIXRGB CON UN ELEMENTO R, COMO
% PROTOSALIDA.
% DOMINIO: TDA:PIXRGB X ENTERO

select_pixrgb_red([X,Y,R|PB],R):- isPixrgb([X,Y,R|PB]).

%SELECT_PIXRGB_GREEN
% UNIFICA EL CUARTO ELEMENTO DE UN TDA:PIXRGB CON UN ELEMENTO G, COMO
% PROTOSALIDA.
% DOMINIO: TDA:PIXRGB X ENTERO

select_pixrgb_green([X,Y,R,G|PB],G):- isPixrgb([X,Y,R,G|PB]).

%SELECT_PIXRGB_BLUE
% UNIFICA EL QUINTO ELEMENTO DE UN TDA:PIXRGB CON UN ELEMENTO B, COMO
% PROTOSALIDA.
% DOMINIO: TDA:PIXRGB X ENTERO

select_pixrgb_blue([X,Y,R,G,B|PB],B):- isPixrgb([X,Y,R,G,B|PB]).

%SELECT_PIXRGB_DEPTH
% UNIFICA EL SEXTO ELEMENTO DE UN TDA:PIXRGB CON UN ELEMENTO D, COMO
% PROTOSALIDA.
% DOMINIO: TDA:PIXRGB X ENTERO

select_pixrgb_depth([X,Y,R,G,B,D|PB],D):- isPixrgb([X,Y,R,G,B,D|PB]).

%MOD_PIXRGB_X
% UNIFICA LOS ELEMENTOS DE UN TDA:PIXRGB Y UN ENTERO X, CON UN
% TDA:PIXRGB SIMILAR AL PRIMER TDA:PIXRGB, PERO CON SU PRIMER
% ELEMENTO CORRESPONDIENTE AL ENTERO X.
% DOMINIO: TDA:PIXRGB X ENTERO X TDA:PIXRGB

mod_pixrgb_x([X|PB],New_X,[New_X|PB]):- isPixrgb([X|PB]),integer(New_X),New_X > -1.

%MOD_PIXRGB_Y
% UNIFICA LOS ELEMENTOS DE UN TDA:PIXRGB Y UN ENTERO Y, CON UN
% TDA:PIXRGB SIMILAR AL PRIMER TDA:PIXRGB, PERO CON SU SEGUNDO
% ELEMENTO CORRESPONDIENTE AL ENTERO Y.
% DOMINIO: TDA:PIXRGB X ENTERO X TDA:PIXRGB

mod_pixrgb_y([X,Y|PB],New_Y,[X,New_Y|PB]):- isPixrgb([X,Y|PB]),integer(New_Y),New_Y > -1.

%MOD_PIXRGB_RED
% UNIFICA LOS ELEMENTOS DE UN TDA:PIXRGB Y UN ENTERO R, CON UN
% TDA:PIXRGB SIMILAR AL PRIMER TDA:PIXRGB, PERO CON SU TERCER
% ELEMENTO CORRESPONDIENTE AL ENTERO R.
% DOMINIO: TDA:PIXRGB X ENTERO X TDA:PIXRGB

mod_pixrgb_red([X,Y,R|PB],New_R,[X,Y,New_R|PB]):- isPixrgb([X,Y,R|PB]), integer(New_R), New_R > -1, New_R < 256.

%MOD_PIXRGB_GREEN
% UNIFICA LOS ELEMENTOS DE UN TDA:PIXRGB Y UN ENTERO R, CON UN
% TDA:PIXRGB SIMILAR AL PRIMER TDA:PIXRGB, PERO CON SU CUARTO
% ELEMENTO CORRESPONDIENTE AL ENTERO R.
% DOMINIO: TDA:PIXRGB X ENTERO X TDA:PIXRGB

mod_pixrgb_green([X,Y,R,G|PB],New_G,[X,Y,R,New_G|PB]):- isPixrgb([X,Y,R,G|PB]), integer(New_G), New_G > -1, New_G < 256.

%MOD_PIXRGB_BLUE
% UNIFICA LOS ELEMENTOS DE UN TDA:PIXRGB Y UN ENTERO G, CON UN
% TDA:PIXRGB SIMILAR AL PRIMER TDA:PIXRGB, PERO CON SU QUINTO
% ELEMENTO CORRESPONDIENTE AL ENTERO G.
% DOMINIO: TDA:PIXRGB X ENTERO X TDA:PIXRGB

mod_pixrgb_blue([X,Y,R,G,B|PB],New_B,[X,Y,R,G,New_B|PB]):- isPixrgb([X,Y,R,G,B|PB]), integer(New_B), New_B > -1, New_B < 256.

%MOD_PIXRGB_DEPTH
% UNIFICA LOS ELEMENTOS DE UN TDA:PIXRGB Y UN ENTERO B, CON UN
% TDA:PIXRGB SIMILAR AL PRIMER TDA:PIXRGB, PERO CON SU SEXTO
% ELEMENTO CORRESPONDIENTE AL ENTERO B.
% DOMINIO: TDA:PIXRGB X ENTERO X TDA:PIXRGB

mod_pixrgb_depth([X,Y,R,G,B,D|PB],New_D,[X,Y,R,G,B,New_D|PB]):- isPixrgb([X,Y,R,G,B,D|PB]), integer(New_D).






