:- module('TDA-pixhex',
           [pixhex/5,isPixhex/1,select_pixhex_x/2,select_pixhex_y/2,select_pixhex_hex/2,select_pixhex_depth/2,mod_pixhex_x/3,mod_pixhex_y/3,mod_pixhex_hex/3,mod_pixhex_depth/3]).

%TDA-PIXHEX
%ENTERO X ENTERO X STRING X ENTERO
%

%PIXHEX
% UNIFICA LOS VALORES ENTREGADOS CON UN TDA:PIXHEX CUYO
% CONTENIDO SON DICHOS VALORES.
% DOMINIO: ENTERO X ENTERO X STRING X ENTERO X TDA:PIXHEX.

pixhex(X,Y,Hex,D,[X,Y,Hex,D]).

%ISPIXHEX
% EVALUA SI UN ELEMENTO INGRESADO ES UN TDA:PIXHEX.
% DOMINIO: ANY

isPixhex([X,Y,Hex,D|[]]):-integer(X),integer(Y),X > -1,Y > -1, isRGBHex(Hex), integer(D).

%SELECT_PIXHEX_X
% UNIFICA EL PRIMER ELEMENTO DE UN TDA:PIXHEX CON UN ELEMENTO X, COMO
% PROTOSALIDA.
% DOMINIO: TDA:PIXHEX X ENTERO

select_pixhex_x([X|PB],X):- isPixhex([X|PB]).

%SELECT_PIXHEX_Y
% UNIFICA EL SEGUNDO ELEMENTO DE UN TDA:PIXHEX CON UN ELEMENTO Y, COMO
% PROTOSALIDA.
% DOMINIO: TDA:PIXHEX X ENTERO

select_pixhex_y([X,Y|PB],Y):- isPixhex([X,Y|PB]).

%SELECT_PIXHEX_HEX
% UNIFICA EL TERCER ELEMENTO DE UN TDA:PIXHEX CON UN ELEMENTO H, COMO
% PROTOSALIDA.
% DOMINIO: TDA:PIXHEX X STRING

select_pixhex_hex([X,Y,H|PB],H):- isPixhex([X,Y,H|PB]).

%SELECT_PIXHEX_DEPTH
% UNIFICA EL CUARTO ELEMENTO DE UN TDA:PIXHEX CON UN ELEMENTO D, COMO
% PROTOSALIDA.
% DOMINIO: TDA:PIXHEX X ENTERO

select_pixhex_depth([X,Y,H,D|PB],D):- isPixhex([X,Y,H,D|PB]).

%MOD_PIXHEX_X
% UNIFICA LOS ELEMENTOS DE UN TDA:PIXHEX Y UN ENTERO X, CON UN
% TDA:PIXHEX SIMILAR AL PRIMER TDA:PIXHEX, PERO CON SU PRIMER
% ELEMENTO CORRESPONDIENTE AL ENTERO X.
% DOMINIO: TDA:PIXHEX X ENTERO X TDA:PIXHEX

mod_pixhex_x([X|PB],New_X,[New_X|PB]):- isPixhex([X|PB]),integer(New_X),New_X > -1.

%MOD_PIXHEX_Y
% UNIFICA LOS ELEMENTOS DE UN TDA:PIXHEX Y UN ENTERO Y, CON UN
% TDA:PIXHEX SIMILAR AL PRIMER TDA:PIXHEX, PERO CON SU SEGUNDO
% ELEMENTO CORRESPONDIENTE AL ENTERO Y.
% DOMINIO: TDA:PIXHEX X ENTERO X TDA:PIXHEX

mod_pixhex_y([X,Y|PB],New_Y,[X,New_Y|PB]):- isPixhex([X,Y|PB]),integer(New_Y),New_Y > -1.

%MOD_PIXHEX_HEX
% UNIFICA LOS ELEMENTOS DE UN TDA:PIXHEX Y UN STRING, CON UN
% TDA:PIXHEX SIMILAR AL PRIMER TDA:PIXHEX, PERO CON SU TERCER
% ELEMENTO CORRESPONDIENTE AL STRING HEXADECIMAL H.
% DOMINIO: TDA:PIXHEX X STRING X TDA:PIXHEX

mod_pixhex_hex([X,Y,H|PB],New_H,[X,Y,New_H|PB]):- isPixhex([X,Y,H|PB]), isHEXHex(New_H).

%MOD_PIXHEX_DEPTH
% UNIFICA LOS ELEMENTOS DE UN TDA:PIXHEX Y UN ENTERO B, CON UN
% TDA:PIXHEX SIMILAR AL PRIMER TDA:PIXHEX, PERO CON SU CUARTO
% ELEMENTO CORRESPONDIENTE AL ENTERO B.
% DOMINIO: TDA:PIXHEX X ENTERO X TDA:PIXHEX

mod_pixhex_depth([X,Y,R,G,B,D|PB],New_D,[X,Y,R,G,B,New_D|PB]):- isPixhex([X,Y,R,G,B,D|PB]), integer(New_D).
